# Generated by Django 4.2.7 on 2023-11-05 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cumples', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cumpleañero',
            options={'ordering': ['fecha_nacimiento'], 'verbose_name': 'Cumpleañero', 'verbose_name_plural': 'Cumpleañeros'},
        ),
        migrations.RenameField(
            model_name='cumpleañero',
            old_name='date_bord',
            new_name='fecha_nacimiento',
        ),
        migrations.AlterModelTable(
            name='cumpleañero',
            table='cumples',
        ),
    ]
