# Generated by Django 4.2.7 on 2023-11-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cumples', '0002_alter_cumpleañero_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cumpleañero',
            options={'ordering': ['mes_cumpleaños', 'dia_cumpleaños'], 'verbose_name': 'Cumpleañero', 'verbose_name_plural': 'Cumpleañeros'},
        ),
        migrations.RemoveField(
            model_name='cumpleañero',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='cumpleañero',
            name='dia_cumpleaños',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cumpleañero',
            name='mes_cumpleaños',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
