# Generated by Django 4.2.7 on 2023-11-05 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cumples', '0003_alter_cumpleañero_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cumpleañero',
            name='dia_cumpleaños',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='cumpleañero',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/cumpleañeros/'),
        ),
        migrations.AlterField(
            model_name='cumpleañero',
            name='mes_cumpleaños',
            field=models.PositiveIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')]),
        ),
    ]
